[projects]

  [projects.default]
  contents = [
    "about",
    "appendix",
    "references",
  ]

  # Full URL, required for the sitemap and robots.txt.
  online_url = "https://deeplearningwithjulia.com"

  # Extra directories to be copied.
  extra_directories = []

  # Port used by serve()
  port = 8004

  output_filename = "DeepLearningWithJulia"
